version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing the lime-compiler gem
      - apt-get update -y
      - apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev nodejs
      - curl -L https://get.rvm.io | bash -s stable --ruby
      - . /etc/profile.d/rvm.sh
      - /usr/local/rvm/scripts/rvm get stable --autolibs=enable
      - /usr/local/rvm/scripts/rvm install ruby-2.3.1
      - /usr/local/rvm/scripts/rvm --default use ruby-2.3.1
      - /usr/local/rvm/scripts/rvm use 2.3.1
      - gem update --system
      - gem install specific_install
      - gem specific_install -l https://github.com/ThreatResponse/lime-compiler.git
      - echo creating required directories
      - mkdir -p build/modules/
      - mkdir -p build/repodata/
      - mkdir -p archive/
  build:
    commands:
      - aws s3 sync build/modules/ s3://threatresponse-lime-modules/modules/
      - aws s3 sync build/modules/ s3://threatresponse-lime-modules/repodata/
      - echo Beginning run of the lime compiler `date`
  post_build:
    commands:
      - echo "Syncing "
