---
docker:
  url: 'unix:///var/run/docker.sock'

repository:
  packager: "lime-compiler info@threatresponse.cloud"
  platform: "linux"

distributions:
  amzn1:
    packager: '/usr/bin/yum'
    packager_args:
      - '-y'
      - '-d1'
    check_package: ['/bin/bash', '-c', '/bin/rpm -qa | grep ']
    kernel_packages: 'yum --showduplicates list kernel-devel'
    kernel_package_match: 'kernel\-devel\.x86_64'
    match_position: 0
    kernel_position: 1
    kernel_package_prefix: 'kernel-devel-'
    source_dir: '/usr/src/kernels'
    source_include_arch?: true
    source_strip: 'kernel-devel-'
    dependencies:
      - 'git'
      - 'make'
      - 'gcc'
  centos:
    packager: '/usr/bin/yum'
    packager_args:
      - '-y'
      - '-d1'
    check_package: ['/bin/bash', '-c', '/bin/rpm -qa | grep ']
    kernel_packages: '/usr/bin/yum --showduplicates list kernel-devel'
    kernel_package_match: 'kernel\-devel\.x86_64'
    match_position: 0
    kernel_position: 1
    kernel_package_prefix: 'kernel-devel-'
    source_dir: '/usr/src/kernels'
    source_include_arch?: true
    source_strip: 'kernel-devel-'
    dependencies:
      - 'git'
      - 'make'
      - 'gcc'
    pre_actions:
      - "/bin/sed -i s/enabled=0/enabled=1/g /etc/yum.repos.d/CentOS-Vault.repo"
  ubuntu:
    packager: '/usr/bin/apt-get'
    packager_args:
      - '-q'
      - '-y'
    check_package: ['/usr/bin/dpkg', '-s', '']
    kernel_packages: '/usr/bin/apt-cache search linux-headers-.*-generic$'
    kernel_package_match: '^linux\-headers\-.*\-generic$'
    match_position: 0
    kernel_position: 0
    kernel_source_postfix: '/build'
    source_dir: '/lib/modules'
    source_include_arch?: false
    source_strip: 'linux-headers-'
    dependencies:
      - 'git'
      - 'make'
      - 'gcc'
      - 'dpkg-dev'
  debian:
    packager: '/usr/bin/apt-get'
    packager_args:
      - '-q'
      - '-y'
    check_package: ['/usr/bin/dpkg', '-s', '']
    kernel_packages: '/usr/bin/apt-cache search linux-headers-*'
    kernel_package_match: '^linux\-headers\-.*(?<!all)\-amd64$'
    match_position: 0
    kernel_position: 0
    kernel_source_postfix: '/build'
    source_dir: '/lib/modules'
    source_include_arch?: false
    source_strip: 'linux-headers-'
    dependencies:
      - 'git'
      - 'make'
      - 'gcc'
      - 'dpkg-dev'

images:
  amzn:
    image: "amazonlinux"
    tag: "latest"
    distribution: 'amzn'
  debian7:
    image: "debian"
    tag: "7"
    distribution: 'debian'
  debian8:
    image: "debian"
    tag: "8"
    distribution: 'debian'
  centos6:
    image: "centos"
    tag: "6"
    distribution: 'centos'
  centos7:
    image: "centos"
    tag: "7"
    distribution: 'centos'
  ubuntu-12.04:
    image: "ubuntu"
    tag: "12.04"
    distribution: "ubuntu"
  ubuntu-14.04:
    image: "ubuntu"
    tag: "14.04"
    distribution: 'ubuntu'
  ubuntu-15.10:
    image: "ubuntu"
    tag: "15.10"
    distribution: "ubuntu"
  ubuntu-16.04:
    image: "ubuntu"
    tag: "16.04"
    distribution: "ubuntu"
  ubuntu-16.10:
    image: "ubuntu"
    tag: "16.10"
    distribution: "ubuntu"
